### ISSUE TITLE
The cropped image is not circular even though the cropping window is a circle

### ISSUE THREAD

**Issue by narayanaraoR** [ArthurHub/Android-Image-Cropper#10]
When the cropping window is a circle, I would like to save just the visible portion of the image (i.e. a circular cropped image). How could I do that?

**Comment by ArthurHub** [comment]
It's by design as there is so such thing as circular bitmap.
There are two ways to handle it:
 1. Create a copy of the bitmap image and draw only the circle part of the original [see here](http://stackoverflow.com/questions/2459916/how-to-make-an-imageview-with-rounded-corners)
 2. On draw to the device (screen) draw only the circle part [see here at the end](http://evel.io/2013/07/21/rounded-avatars-in-android/)

The second option is better for performance and handling all possible images, that's what I did.

**Comment by narayanaraoR** [comment]
@ArthurHub Thanks so much for the links. I will try to implement these in my app.
