### ISSUE TITLE
setInitialRotation doesn't work until you zoom/unzoom image

### ISSUE THREAD

**Issue by Timenote** [ArthurHub/Android-Image-Cropper#106]
Hi,

setInitialRotation doesn't work until you zoom/unzoom image.

(on Samsung Galaxy S6 running Android 6.0.1)

Really nice library, congrats !

**Comment by ArthurHub** [comment]
It is possible that the issue is with exif data.
When you explicitly set the initial rotation it is NOT in addition to the exit data but overrides it.
Example:
If the image has exif data telling it to be rotated by 90 degrees then the library will read it and rotate it for you.
If you set initial rotation to be 90 degrees then it will also rotate it by 90 degrees resulting in the same image rotation so you may think that rotation didn't work at all.
In that case you have to read the exit data and add the required rotation to it.

see `BitmapUtils.rotateBitmapByExif` method on how to read exif data.

Let me know if this was the issue.

**Comment by zzhang1** [comment]
Hi, this is a very belated comment, but the issue seems to be similar to what I see, with:

```
CropImage.activity(mCurrentPhotoURI)
                                .setInitialRotation(mCropRotation)
                                .setInitialCropWindowRectangle(mRotatedRect)
                                .start(this);
```

The rotation is properly set and accounts for EXIF, but visually, it doesn't show until I drag the crop rectangle somewhere such that the image view pans or zooms. Then the image view suddenly refreshes to the expected rotation.

It only happens when initial rotation is used in combination with a setInitialCropWindowRectangle() -- with just a setInitialRotation().start(), it works fine as expected.

If you read this, please don't feel obligated to do anything--I just wanted to document the behavior. Thank you and congratulations on such a lightweight, comprehensive, and fun cropping library!
