### ISSUE TITLE
About the method setImageURI

### ISSUE THREAD

**Issue by gmm932** [ArthurHub/Android-Image-Cropper#159]
Sometimes,when I crop a picture fully(3.7M),
setImageURI it dosen't work, the picture can not show,but crop part of the picture is worked,why?

I try use:
Bitmap bitmap = MediaStore.Images.Media.getBitmap(getContentResolver(), croppedImgUri);
xxxx.setImageBitmap(bitmap);
it dosen't work too.
some size limit about setImageURI?

**Comment by ArthurHub** [comment]
What version of the library do you use?

**Comment by gmm932** [comment]
The version is 2.3.0

**Comment by ArthurHub** [comment]
Hmmm... `setImageURI` doesn't exist in this version, do you mean `setImageUriAsync`?

The issue is, probably, with image dimensions, Android restrict rendering images that have dimension (width or height) higher than 1012/2024/4048 (depending on device).

So when you load the image yourself and its dimensions were larger than allowed Android will not render it so you get a black screen. But the image data is still there so you can crop it.

If you use `setImageUriAsync` I have code to handle it, loading sampled image to lower its dimensions.

Can you verify that you use the latest version and check the dimensions of the problematic image?

**Comment by gmm932** [comment]
I use `setImageURI`  just like your code 
` ((ImageView) findViewById(R.id.quick_start_cropped_image)).setImageURI(result.getUri());` in `onActivityResult` when I crop successed and in this method I upload the picture use retrofit
`MultipartBody.Part requestBody = MultipartHelper.prepareFilePart(ApiInterface.KEY_USER_PIC, croppedImgUri);` successed. 
Also I can download  it and show in ImageView. I think is not probably about  Android restrict render.

**Comment by ArthurHub** [comment]
The method `setImageURI` was removed in 2.0.0, it's just not there anymore.
Your are definitely using an older version, I strongly advice you to update.

**Comment by gmm932** [comment]
OK,I will update, Thank you for your patience.
