### ISSUE TITLE
Issue with item #3 in the 'using activity' in the README.

### ISSUE THREAD

**Issue by jake32321** [ArthurHub/Android-Image-Cropper#288]
An image uri needs to be included in:

```java 
CropImage.activity()
                .setGuidelines(CropImageView.Guidelines.ON)
                .start(this);
```

this should be changed to:

```java 
CropImage.activity(imageUri)
                .setGuidelines(CropImageView.Guidelines.ON)
                .start(this);
```

This is due to what I've seen when implementing this.

**Comment by ArthurHub** [comment]
Actually, the URI is optional since *v2.4.0* so you can pass null to `CropImage.activity` method.
You are right that the documentation is incorrect, I have [added](https://github.com/ArthurHub/Android-Image-Cropper/commit/6257fb542d4d37fdf8e108420be2e7fd3e5e4e88) overloaded method that doesn't receive any parameter.
Sorry for the mistake and thank you for pointing it out.
