### ISSUE TITLE
getCroppedImage(int reqWidth, int reqHeight) doesn't work properly

### ISSUE THREAD

**Issue by davidaik** [ArthurHub/Android-Image-Cropper#43]
CropImageView.getCroppedImage(int reqWidth, int reqHeight) doesn't return a Bitmap of required dimensions.

I hope this issue isn't overlooked like the one with getActualCropRect() being not really "actual".

**Comment by ArthurHub** [comment]
The requested width/height is an optimization to down-sample the cropped part to specific size, it may and probably will not be the exact size, see [Loading Large Bitmaps Efficiently](http://developer.android.com/training/displaying-bitmaps/load-bitmap.html).

Also please be respectful of open source projects.

**Comment by davidaik** [comment]
Oh, I'm sorry, I didn't mean to sound disrespectful. I just wish to express my concern over the fact that to many, "reqWidth" might seem to mean "required width" and I think this would cause a lot of confusion when the resultant Bitmap isn't of the required width that might be expected. In my testing, I used reqWidth = 300 and reqHeight = 300 and the resultant Bitmap is sometimes ~300x300 and sometimes ~600x600 or ~400x400.

This confusion would be similar to the one that getActualCropRect() might bring.

Sorry again if I sounded rude.

**Comment by davidaik** [comment]
@ArthurHub Should I make a PR after adding a getCroppedImageExactSize(int reqWidth, int reqHeight) method? Do you think such a method might be a useful addition?

**Comment by ArthurHub** [comment]
I understand the naming issue, I have used those names because Android uses them in bitmap decoding options. 
Obviously better documentation will help, but documentation is always an issue. 

I don't think image resize is appropriate for the library, it counts as post processing that is beyond the scope of getting the cropped bitmap. 
The only reason reqWidth/reqHeight is there is that it can be done during the bitmap decoding and is important for performance.

**Comment by davidaik** [comment]
hmm I think you're right.
