### ISSUE TITLE
failed to get cropped oval shape in new version but other shapes i m able to get perfectly..

### ISSUE THREAD

**Issue by altaf2892** [ArthurHub/Android-Image-Cropper#53]
**tried like for oval shape**

 ```
cropImageView.setImageBitmap(bitmapOrignal);
                cropImageView.setCropShape(CropImageView.CropShape.OVAL);
bitmapOrignal=cropImageView.getCroppedImage();
                       iv_toedit.setImageBitmap(bitmapOrignal);
```
**tried like for rectangle**
```
```
`  cropImageView.setImageBitmap(bitmapOrignal);
                cropImageView.setCropShape(CropImageView.CropShape.RECTANGLE);
bitmapOrignal=cropImageView.getCroppedImage();
                       iv_toedit.setImageBitmap(bitmapOrignal);`
```

**Comment by ArthurHub** [comment]
The resulting cropped image is always rectangular simply because bitmaps are.
Usually the oval shape is created during rendering of the image, there are many solutions for it.
But if you do want the resulting image pixels to reflect the oval shape you can use `CropImage.toOvalBitmap(Bitmap)` helper method that does exactly that.
