### ISSUE TITLE
How to customize back button on CropImageActivity

### ISSUE THREAD

**Issue by cgupta3131** [ArthurHub/Android-Image-Cropper#758]
It seems that whenever I press the back button on CropImageActivity, my app just crashes.
Is there a way to customize the back button (Top left on the UI page), so that I can take it back to my original activity,

**Comment by oescob16** [comment]
Did you fix the problem? I ask because I have the same problem:(

**Comment by oescob16** [comment]
@ArthurHub Can you help us please?:(

**Comment by oescob16** [comment]
@cgupta3131 ?

**Comment by cgupta3131** [comment]
Hey! I tried but was in vain!!

**Comment by oescob16** [comment]
@cgupta3131 I already fix the problem:
In the onActivityResult() method we have a variable called data, which stores the image we choose to crop. Therefore, if we press the back button, data will become null (because we did not choose an image), causing the line _val: CropImage.ActivityResult = CropImage.getActivityResult (data) _ to fail.
**This were the changes that I implemented to make to my code work:**
if(requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE && **data != null**){
       // Store image in the firebase storage and database logic
} else {  // data is null, go back to the setup activity
       **val selfIntent = Intent(this@SetupActivity,SetupActivity::class.java)
       selfIntent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)
       startActivity(selfIntent)**
}

**Comment by Shazie22** [comment]
Thank you @oescob16  this just helped me big time

**Comment by cgupta3131** [comment]
The issue is fixed, view the last comment for more details
