### ISSUE TITLE
Is it possible to change the shape of the guideline?

### ISSUE THREAD

**Issue by soonmyeong2** [ArthurHub/Android-Image-Cropper#792]
![image](https://user-images.githubusercontent.com/38336997/94949617-2d2bcb00-051c-11eb-891f-0ca2c7ee257f.png)
![image](https://user-images.githubusercontent.com/38336997/94949639-387ef680-051c-11eb-96ae-44477897136c.png)

I want to add a circular shape to the square as shown in the example picture.
The result should be the same as Rectangle Crop. I just want to add a circular guide.

Is that possible?

**Comment by rahat14** [comment]
use this
       CropImage.activity()
                .setGuidelines(CropImageView.Guidelines.ON)
                .setAspectRatio(1, 1)
                .setCropShape(CropImageView.CropShape.OVAL) //shaping the image
                .start(ProfileActivity.this);

**Comment by soonmyeong2** [comment]
It is one of the good alternatives. But I want a circle inside a rectangle. Non-square

> use this
> CropImage.activity()
> .setGuidelines(CropImageView.Guidelines.ON)
> .setAspectRatio(1, 1)
> .setCropShape(CropImageView.CropShape.OVAL) //shaping the image
> .start(ProfileActivity.this);

**Comment by Canato** [comment]
Hey!

I start a new project to handover this library
https://github.com/CanHub/Android-Image-Cropper

The ideia is that we keep improving because this project don’t have updates since `2018` 
Hope I can count with your help.

Open to contribute, next pieces of work will be Android 11 permissions, refactor into Kotlin and ActivityContract

**Comment by soonmyeong2** [comment]
I achieved my goal by modifying the ```CropOverlayView.java``` file. Thank you all.
