### ISSUE TITLE
JCenter to be sunset on 2020-05-01

### ISSUE THREAD

**Issue by petedoyle** [ArthurHub/Android-Image-Cropper#815]
Hi! Just a heads up- JCenter will no longer be available after 2020-05-01:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Just a note in case it makes sense to publish releases somewhere new (Maven Central, etc.)

Best,
Pete

**Comment by tfcporciuncula** [comment]
Here's a couple of links that might help with the migration:

https://chris.banes.dev/publishing-to-maven-central/
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/PUBLISHING.asciidoc

**Comment by Canato** [comment]
THIS LIBRARY IS NOT MAINTAINED, PLEASE READ THIS #806

I start a new project to handover this library
https://github.com/CanHub/Android-Image-Cropper

The ideia is that we keep improving because this project don’t have updates since 2018
Hope I can count with your help.

Open to contribute, next pieces of work will be Android 11 permissions, refactor into Kotlin and ActivityContract
