### ISSUE TITLE
Bitmap too large to be uploaded into a texture (3031x4169, max=4096x4096)

### ISSUE THREAD

**Issue by chandrahasan** [ArthurHub/Android-Image-Cropper#84]
Hi ,  First your library is so useful.

When I choose large crop size area then I got this error ,
```
Bitmap too large to be uploaded into a texture (3031x4169, max=4096x4096)
Some time also get  out of memory error.
```
This is getting after onGetCroppedImageComplete done, **I tried to set bitmap to my ImageView here is error** .

I picked image from gallery  .  Kindly advise how to solve this issue.

**Comment by ArthurHub** [comment]
Android devices have a limit to the size of image they can render, see `BitmapUtils.calculateInSampleSizeByMaxTextureSize` to how I get that limit value, so you need to limit the size of the image you are getting.

It seems you are handling a very large images so I advice to use sampling, use `.getCroppedImageAsync(int reqWidth, int reqHeight)` overload to limit cropped image size.
See [Loading Large Bitmaps Efficiently](http://developer.android.com/training/displaying-bitmaps/load-bitmap.html) on what sampling is.

Note, by design getting cropped image has no built-in protection from out-of-memory error, you can do it using the requested width/height starting with large value and lowering it until success.

**Comment by chandrahasan** [comment]
**Thanks for your immediate response,**  

Now I pass with Width & Height  by using below , Now its working fine.
```
int xDim=iv_chooseImage.getWidth();
int yDim=iv_chooseImage.getHeight();
```
