### ISSUE TITLE
How do you handle image exif data? I need to handle it in the original image captured by Samsung camera, please help.

### ISSUE THREAD

**Issue by trramsiq** [ArthurHub/Android-Image-Cropper#90]
On images returned by CropImage.PICK_IMAGE_CHOOSER_REQUEST_CODE the ExifInterface.TAG_ORIENTATION is always the same what ever orientation the phone is held in.

**Comment by ArthurHub** [comment]
ok... what's the problem/question/issue?

**Comment by trramsiq** [comment]
I have to upload it to a server and cannot rotate it correctly due to this error

**Comment by ArthurHub** [comment]
what error? I don't understand.

**Comment by trramsiq** [comment]
An image taken in portrait is shown in landscape and vice versa.

**Comment by ArthurHub** [comment]
during cropping?

**Comment by trramsiq** [comment]
No cropping handles it correctly. But just using the image picker gives me the issue.

**Comment by ArthurHub** [comment]
So the original image taken by Samsung camera has exif orientation metadata.
How is this issue relevant for the cropping library?

**Comment by trramsiq** [comment]
It's the Image picker not the cropping library.
parsing the image to the cropping library returns the image correctly.
The problem is only with the image picker on samsung devices.

**Comment by ArthurHub** [comment]
Yes, Android SDK image picker result works this for Samsung devices.
Did you try googling this?

**Comment by trramsiq** [comment]
A bit, but it seems that you handle this issue in the crop library somehow...

**Comment by ArthurHub** [comment]
by reading the exif data of the image and then rotating it by the required amount using matrix transformation in ImageView.

It is not a bug, it's how image capture works in the world and specifically how Samsung decided to implement their hardware. 
Most importantly it has nothing to do with the cropping library.

It would be nice if you would invest a bit more time researching the issues you encounter and ask more relevant question.
Instead of "2.2.0 ExifInterface.TAG_ORIENTATION always 6 on samsung galaxy s4 mini" that assumes there is an issue with the library after a bit of reading you could ask "How do you handle image exif data? I need to handle it in the original image captured by Samsung camera, please help."

**Comment by trramsiq** [comment]
Sure!

I don't know how to handle the exif data since it is always the same whatever the orientation of the phone while taking the picture.
Please help

**Comment by ArthurHub** [comment]
but then, if you google it, you will get the answers yourself...
https://www.google.co.il/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=android%20samsung%20camera%20orientation

http://stackoverflow.com/questions/25217225/camera-orientation-in-samsung-device-issue
http://stackoverflow.com/questions/18203369/camera-capture-orientation-on-samsung-devices-in-android

**Comment by trramsiq** [comment]
It really seems like I'm annoying you now. 
I've already been through those.
This is why I'm here! I thought that maybe Maybe you will have an idea since you somehow got it working in cropping tool.
But thanks anyway!

**Comment by ArthurHub** [comment]
I have already told you what I did "by reading the exif data of the image and then rotating it by the required amount using matrix transformation in ImageView."
The stackoverflow answers gives a sample code to read and manipulate image.
If somehow they don't answer you questions and no one every encountered the same problem that you have you should ask a question on stackoverflow, that's what it's for.
